name: CI for Automated Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Dependencies
      run: |
        npm install

    - name: Run HTML Validation
      run: |
        npm install -g htmlhint
        npx htmlhint index.html

    - name: Run CSS Linter
      run: |
        npm install -g stylelint
        npx stylelint "**/*.css"

    - name: Run Docker Linter
      if: exists('Dockerfile')
      uses: hadolint/hadolint-action@v2
      with:
        dockerfile: Dockerfile
