name: Test and Validation Deployment

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      REGISTRY_LOGIN_SERVER: ${{ secrets.REGISTRY_LOGIN_SERVER }}
      IMAGE_NAME: ${{ secrets.REGISTRY_LOGIN_SERVER }}/swe40006-project
      CONTAINER_NAME: swe40006-project-test-container
      RESOURCE_GROUP: ${{ secrets.RESOURCE_GROUP }}
      LOCATION: 'australia southeast'

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Node.js 20
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install Dependencies for Stylelint
      run: |
        sudo npm uninstall -g stylelint
        sudo apt-get update
        sudo apt-get install -y nodejs npm
        npm install stylelint@14 stylelint-config-standard@24 --save-dev

    - name: Create Stylelint Configuration
      run: |
        echo '{
          "extends": "stylelint-config-standard",
          "rules": {
            "font-family-no-missing-generic-family-keyword": true,
            "shorthand-property-no-redundant-values": true,
            "no-descending-specificity": true,
            "color-hex-length": "short",
            "declaration-block-no-duplicate-properties": true,
            "selector-pseudo-class-no-unknown": true
          }
        }' > .stylelintrc.json

    - name: Run HTML Linter
      run: npx htmlhint index.html

    - name: Run CSS Linter with Auto-Fix
      run: npx stylelint "**/*.css" --fix

    - name: Run Docker Linter using Hadolint via Docker
      run: docker run --rm -i hadolint/hadolint < Dockerfile

    - name: Build Docker Image for Testing
      run: docker build -t $IMAGE_NAME:${{ github.sha }} .

    - name: Run Docker Container for Testing
      run: docker run -d --name $CONTAINER_NAME $IMAGE_NAME:${{ github.sha }}

    - name: Run Integration Tests
      run: echo "Running integration tests against the container"
      
    - name: Cleanup Docker Container
      run: docker rm -f $CONTAINER_NAME
