name: Test and Validate Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set Up Node.js Environment
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Dependencies
      run: npm install

    - name: Run HTML Linter
      run: |
        npm install -g htmlhint
        npx htmlhint index.html

    - name: Run CSS Linter
      run: |
        npm install -g stylelint
        npx stylelint "**/*.css"

    - name: Run Unit Tests
      run: npm test 
    - name: Run Docker Linter
      uses: hadolint/hadolint-action@v2
      with:
        dockerfile: Dockerfile

    - name: Build Docker Image for Testing
      run: |
        docker build . -t project-image:${{ github.sha }}

    - name: Run Docker Container for Testing
      run: |
        docker run -d --name test-container project-image:${{ github.sha }}
    
    - name: Run Integration Tests (if applicable)
      run: |
        # Add your integration tests here
        echo "Running integration tests"

    - name: Cleanup Docker Container
      run: docker rm -f test-container
