name: Test and Validation Deployment

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      REGISTRY_LOGIN_SERVER: ${{ secrets.REGISTRY_LOGIN_SERVER }}
      IMAGE_NAME: ${{ secrets.REGISTRY_LOGIN_SERVER }}/swe40006-project
      CONTAINER_NAME: swe40006-project-test-container
      RESOURCE_GROUP: ${{ secrets.RESOURCE_GROUP }}
      LOCATION: 'australia southeast'

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Node.js 20
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install HTMLHint and Stylelint Locally
      run: |
        sudo apt-get update
        sudo apt-get install -y nodejs npm
        npm install stylelint stylelint-config-standard --save-dev
        echo '{
          "extends": "stylelint-config-standard",
          "rules": {
            "indentation": 2,
            "number-leading-zero": "always",
            "string-quotes": "double"
          }
        }' > .stylelintrc.json

    - name: Run HTML Linter
      run: npx htmlhint index.html

    - name: Run CSS Linter with Auto-Fix
      run: npx stylelint "**/*.css" --fix

    - name: Run Docker Linter using Hadolint via Docker
      run: docker run --rm -i hadolint/hadolint < Dockerfile

    - name: Build Docker Image for Testing
      run: docker build -t $IMAGE_NAME:${{ github.sha }} .

    - name: Run Docker Container for Testing
      run: docker run -d --name $CONTAINER_NAME $IMAGE_NAME:${{ github.sha }}

    - name: Run Integration Tests
      run: echo "Running integration tests against the container"
      
    - name: Cleanup Docker Container
      run: docker rm -f $CONTAINER_NAME
